// Mocks generated by Mockito 5.0.10 from annotations
// in nomoca_flutter/test/presentation/favorite_list_view_local_id_dialog_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:nomoca_flutter/data/entity/database/user.dart' as _i5;
import 'package:nomoca_flutter/data/entity/remote/favorite_entity.dart' as _i7;
import 'package:nomoca_flutter/data/entity/remote/favorite_patient_card_entity.dart'
    as _i2;
import 'package:nomoca_flutter/data/repository/fetch_favorite_list_repository.dart'
    as _i6;
import 'package:nomoca_flutter/data/repository/get_favorite_patient_card_repository.dart'
    as _i8;
import 'package:nomoca_flutter/data/repository/update_favorite_repository.dart'
    as _i9;
import 'package:nomoca_flutter/data/repository/update_local_id_repository.dart'
    as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeFavoritePatientCardEntity extends _i1.Fake
    implements _i2.FavoritePatientCardEntity {}

/// A class which mocks [UpdateLocalIdRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateLocalIdRepository extends _i1.Mock
    implements _i3.UpdateLocalIdRepository {
  MockUpdateLocalIdRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> updateLocalId(
          {int? userId, int? institutionId, String? localId}) =>
      (super.noSuchMethod(
          Invocation.method(#updateLocalId, [], {
            #userId: userId,
            #institutionId: institutionId,
            #localId: localId
          }),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as _i4.Future<void>);
  @override
  String getAuthenticationToken(_i5.User? user) =>
      (super.noSuchMethod(Invocation.method(#getAuthenticationToken, [user]),
          returnValue: '') as String);
}

/// A class which mocks [FetchFavoriteListRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchFavoriteListRepository extends _i1.Mock
    implements _i6.FetchFavoriteListRepository {
  MockFetchFavoriteListRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i7.FavoriteEntity>> fetchList() => (super.noSuchMethod(
          Invocation.method(#fetchList, []),
          returnValue:
              Future<List<_i7.FavoriteEntity>>.value(<_i7.FavoriteEntity>[]))
      as _i4.Future<List<_i7.FavoriteEntity>>);
  @override
  String getAuthenticationToken(_i5.User? user) =>
      (super.noSuchMethod(Invocation.method(#getAuthenticationToken, [user]),
          returnValue: '') as String);
}

/// A class which mocks [GetFavoritePatientCardRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetFavoritePatientCardRepository extends _i1.Mock
    implements _i8.GetFavoritePatientCardRepository {
  MockGetFavoritePatientCardRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.FavoritePatientCardEntity> get(
          {int? userId, int? institutionId}) =>
      (super.noSuchMethod(
              Invocation.method(
                  #get, [], {#userId: userId, #institutionId: institutionId}),
              returnValue: Future<_i2.FavoritePatientCardEntity>.value(
                  _FakeFavoritePatientCardEntity()))
          as _i4.Future<_i2.FavoritePatientCardEntity>);
  @override
  String getAuthenticationToken(_i5.User? user) =>
      (super.noSuchMethod(Invocation.method(#getAuthenticationToken, [user]),
          returnValue: '') as String);
}

/// A class which mocks [UpdateFavoriteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateFavoriteRepository extends _i1.Mock
    implements _i9.UpdateFavoriteRepository {
  MockUpdateFavoriteRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> updateFavorite({int? institutionId}) => (super.noSuchMethod(
      Invocation.method(#updateFavorite, [], {#institutionId: institutionId}),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future.value()) as _i4.Future<void>);
  @override
  String getAuthenticationToken(_i5.User? user) =>
      (super.noSuchMethod(Invocation.method(#getAuthenticationToken, [user]),
          returnValue: '') as String);
}
