// Mocks generated by Mockito 5.0.10 from annotations
// in nomoca_flutter/test/presentation/notification_list_integration_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:nomoca_flutter/data/entity/database/user.dart' as _i5;
import 'package:nomoca_flutter/data/entity/remote/notification_entity.dart'
    as _i4;
import 'package:nomoca_flutter/data/repository/fetch_notification_list_repository.dart'
    as _i2;
import 'package:nomoca_flutter/data/repository/update_read_post_repository.dart'
    as _i6;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [FetchNotificationListRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchNotificationListRepository extends _i1.Mock
    implements _i2.FetchNotificationListRepository {
  MockFetchNotificationListRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.NotificationEntity>> fetchList() =>
      (super.noSuchMethod(Invocation.method(#fetchList, []),
              returnValue: Future<List<_i4.NotificationEntity>>.value(
                  <_i4.NotificationEntity>[]))
          as _i3.Future<List<_i4.NotificationEntity>>);
  @override
  String getAuthenticationToken(_i5.User? user) =>
      (super.noSuchMethod(Invocation.method(#getAuthenticationToken, [user]),
          returnValue: '') as String);
}

/// A class which mocks [UpdateReadPostRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateReadPostRepository extends _i1.Mock
    implements _i6.UpdateReadPostRepository {
  MockUpdateReadPostRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> updateReadPost({int? notificationId}) => (super.noSuchMethod(
      Invocation.method(#updateReadPost, [], {#notificationId: notificationId}),
      returnValue: Future<void>.value(),
      returnValueForMissingStub: Future.value()) as _i3.Future<void>);
  @override
  String getAuthenticationToken(_i5.User? user) =>
      (super.noSuchMethod(Invocation.method(#getAuthenticationToken, [user]),
          returnValue: '') as String);
}
