// Mocks generated by Mockito 5.0.10 from annotations
// in nomoca_flutter/test/presentation/sign_up_view_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:nomoca_flutter/data/repository/create_user_repository.dart'
    as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: comment_references
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [CreateUserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateUserRepository extends _i1.Mock
    implements _i2.CreateUserRepository {
  MockCreateUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> createUser({String? mobilePhoneNumber, String? nickname}) =>
      (super.noSuchMethod(
          Invocation.method(#createUser, [],
              {#mobilePhoneNumber: mobilePhoneNumber, #nickname: nickname}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future.value()) as _i3.Future<void>);
}
