// Mocks generated by Mockito 5.0.15 from annotations
// in nomoca_flutter/test/presentation/sign_up_view_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:nomoca_flutter/data/entity/remote/authentication_entity.dart'
    as _i2;
import 'package:nomoca_flutter/data/repository/authentication_repository.dart'
    as _i5;
import 'package:nomoca_flutter/data/repository/create_user_repository.dart'
    as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeAuthenticationEntity_0 extends _i1.Fake
    implements _i2.AuthenticationEntity {}

/// A class which mocks [CreateUserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateUserRepository extends _i1.Mock
    implements _i3.CreateUserRepository {
  MockCreateUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> createUser({String? mobilePhoneNumber, String? nickname}) =>
      (super.noSuchMethod(
          Invocation.method(#createUser, [],
              {#mobilePhoneNumber: mobilePhoneNumber, #nickname: nickname}),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [AuthenticationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthenticationRepository extends _i1.Mock
    implements _i5.AuthenticationRepository {
  MockAuthenticationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AuthenticationEntity> authentication(
          {String? mobilePhoneNumber, String? authCode}) =>
      (super.noSuchMethod(
              Invocation.method(#authentication, [],
                  {#mobilePhoneNumber: mobilePhoneNumber, #authCode: authCode}),
              returnValue: Future<_i2.AuthenticationEntity>.value(
                  _FakeAuthenticationEntity_0()))
          as _i4.Future<_i2.AuthenticationEntity>);
  @override
  String toString() => super.toString();
}
